In [11]:
import numpy as np

In [12]:
a = np.array([30, 10, 60])
b = np.array([10, 10, 30, 40, 10])

In [13]:
c = np.array(((a[0]+a[1]*0.5), (a[-1]+a[1]*0.5)))
c

array([35., 65.])

In [14]:
d = np.append(b, np.max(b)*(c[0]/c[1]))
d

array([10.        , 10.        , 30.        , 40.        , 10.        ,
       21.53846154])

In [16]:
np.append(a,b)

array([30, 10, 60, 10, 10, 30, 40, 10])

In [5]:
e = d/sum(d)*100
e

array([ 8.2278481 ,  8.2278481 , 24.6835443 , 32.91139241,  8.2278481 ,
       17.72151899])

In [6]:
x = np.array([0,1,2])
y = np.array([1,2,3])

In [9]:
sum((x,y))

array([1, 3, 5])

In [17]:
x = (0,1,2,3)
y = (1,1,2,3)

In [20]:
sum((np.array(x),np.array(y)))

array([1, 2, 4, 6])